### ISSUE TITLE
Decide what front end framework to use

### ISSUE THREAD

**Issue by yohanneshabte** [yohanneshabte/SalaryPerformanceMgmt#10]
### We have to choose what Front end framework we have to use. Here are a couple of the choices we have:

1. React
2. Vue.js (I think easiest)
3. Angular
4. Anything else you might want

- @raswa634 Let me know which one you want to go with, and I can send you a tutorial I have for it. 
- We can use _Bootstrap_ to minimize the CSS we have to write. Also let me know if you need a tutorial for that.

**Comment by raswa634** [comment]
@yohanneshabte sure we can go with Vue.js for front-end framework

**Comment by raswa634** [comment]
https://www.figma.com/file/0Iqwu3bfB6pPAsqiq6nYY8/SalaryPerformanceMgmt?node-id=48%3A2
this is how you want me to develop the front-end?

**Comment by yohanneshabte** [comment]
- yes. Vue.js is great! 
- For the Figma you can start with to implement as much of that design, but @ThauTran is working on it in real time so you should communicate with him on the details. Plus we can discuss the overall design(with everyone) to see if they agree with it going forward.

**Comment by yohanneshabte** [comment]
- There website is [Vuejs.org](https://vuejs.org)
- You can use the [tutorial here](https://www.linkedin.com/learning/vue-js-for-web-designers/get-started-with-the-popular-vue-javascript-framework?u=57684185) to learn most important things for Vue.js
- Most of your sprint for next week is just setting up our development environment using Vue, you can also create components once @ThauTran is okay with his design. But watch the tutorials mostly.
- To setup your files and server you can do this in cmd.(you will learn more about it in the tutorial btw)
```bash
npm install -g @vue/cli
# This will install Vue Command Line Interface on your computer
vue create project-name-here
# This will create the whole initial scaffolding for our project so you can start working on it
yarn serve
```
***
#### This should be your result
<img width="864" alt="Screen Shot 2020-02-09 at 3 25 02 PM" src="https://user-images.githubusercontent.com/54902916/74110291-eb937d80-4b50-11ea-867c-ecbced02fc74.png">
<img width="538" alt="Screen Shot 2020-02-09 at 3 28 27 PM" src="https://user-images.githubusercontent.com/54902916/74110294-f1895e80-4b50-11ea-902f-9aa61da420f7.png">

- Then you can run it on your browser by going to localhost:8080. After you have done that you can upload the project folder to a new branch inside the frontend folder in GitHub. Let me know when you are done so we can close this issue.

**Comment by yohanneshabte** [comment]
- Actually I already created the branch for you [here](https://github.com/yohanneshabte/SalaryPerformanceMgmt/tree/frontend-framework-scaffolding), just push to it there inside the frontend folder. Check out #11. Because there are lots of files uploading will be hard, so you have to have GitHub desktop installed and push your changes from there. Here is the step if you haven't used it before.
1. Open(clone) this repo with GitHub desktop 
2. Switch to the branch 
3. You will find frontend folder in there.
4. After you go inside that directory with your cmd, you can start working on the steps above(creating the project).
5. Then back on GitHub desktop commit and publish your changes.
6. Let me know when you are done.

**Comment by raswa634** [comment]
@yohanneshabte Sure, right now I will be working on tutorial. Actually my laptop broke down and I am getting another one today so I will setup files and server by the end of today.

**Comment by yohanneshabte** [comment]
No worries!  Great let me know how it goes.

**Comment by raswa634** [comment]
@yohanneshabte I see you on figma, actually what are all those design for? Are we designing same thing for GUI or what?

**Comment by yohanneshabte** [comment]
I am not exactly sure.. its @ThauTran work. but I think he described most of what he is doing here #7 .. check out the link or you can also ask him act the specifics
