### ISSUE TITLE
Create salary, roles related entities

### ISSUE THREAD

**Issue by yohanneshabte** [yohanneshabte/SalaryPerformanceMgmt#4]
Here is the link to the lucid chart, where @zele123 making the ERD
[LucidChart ERD](https://www.lucidchart.com/documents/edit/60da6a3d-370d-44e1-9db4-a642eaa45303/0_0?shared=true&existing=1&token=622ecf6bf229ca3ba1b00e6d316c6b7af3fefc00-eml%3Dyohannes.habte%2540mnsu.edu%26ts%3D1580858226679%26uid%3D139369057&docId=60da6a3d-370d-44e1-9db4-a642eaa45303)

**Comment by yohanneshabte** [comment]
@zele123 close this issue when you finish designing the ERD so that I can start working on the scripts to add the tables and constraint keys.

**Comment by zele123** [comment]
I have done this.
