### ISSUE TITLE
Assign relationships to the tables

### ISSUE THREAD

**Issue by yohanneshabte** [yohanneshabte/SalaryPerformanceMgmt#6]
#### For all tables we have at this point:
- [ ] create all the one to many, one to one relationships where necessary
- [ ] add the constraints(Foreign key, primary key)

@Evan-Sack let me know if you can help double check if we got it right once we have the ERD going for few tables.

**Comment by yohanneshabte** [comment]
@zele123 you can start working on this once you have issue #3, #4, #5 is done.

**Comment by zele123** [comment]
I have done this
